id: P000737
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17432
  title: བརྡ་སྤྲོད་རིག་པའི་སྤྱི་དོན།
  author: ''
  volumes:
    a8a29610e5de449facbe5b375e45df00:
      image_group_id: I4PD3007
      title: ''
      volume_number: 1
      total_pages: 248
      base_file: v001.txt
